"""Recognize PSX/Sega CD using only first-track service sectors, not disc scans.

SPDX-License-Identifier: BSD-3-Clause
"""

import re
from collections.abc import Callable
from pathlib import Path

from ...errors import SourceError
from .chd_reader import FRAME_BYTES, ChdReader


TRACK = rb"TRACK:1 TYPE:(\S+) SUBTYPE:(?:NONE|RW|RW_RAW) FRAMES:(\d+)"
GAPS = rb" PREGAP:(\d+) PGTYPE:(\S+) PGSUB:(?:NONE|RW|RW_RAW) POSTGAP:(\d+)"
DATA_OFFSETS = {b"MODE1": 0, b"MODE1_RAW": 16, b"MODE2": 8, b"MODE2_FORM1": 0, b"MODE2_RAW": 24}


def detect_platform(path: Path) -> str:
    """Identify a self-contained CD CHD automatically; unknown/ambiguous images are rejected."""

    with ChdReader(path) as reader:
        metadata = reader.read_metadata(b"CHT2")
        modern = metadata is not None

        if metadata is None:
            metadata = reader.read_metadata(b"CHTR")

        match = re.fullmatch(TRACK + (GAPS if modern else b""), metadata or b"")

        if match is None:
            raise SourceError("Missing or invalid CHD first-track metadata", path=path)

        kind, frames = match[1], int(match[2])

        if kind not in DATA_OFFSETS:
            raise SourceError("Unsupported CHD first-track data mode", path=path)

        # A V-prefixed pregap is stored in the image; other pregaps are generated by the player.
        pregap = int(match[3]) if modern else 0
        start = pregap if modern and match[4].startswith(b"V") else 0

        if frames - start <= 16 or frames * FRAME_BYTES > reader.logical_bytes:
            raise SourceError("Invalid or too short CHD first track", path=path)

        def read_sector(number: int) -> bytes:

            if number < 0 or number >= frames - start:
                raise SourceError("CHD service sector outside the first track", path=path)

            frame = reader.read_frame(start + number)
            offset = DATA_OFFSETS[kind]

            if kind in (b"MODE1_RAW", b"MODE2_RAW"):
                mode = 1 if kind == b"MODE1_RAW" else 2

                if frame[:12] != b"\0" + b"\xff" * 10 + b"\0" or frame[15] != mode:
                    raise SourceError("Invalid CHD raw data-sector header", path=path)

            if kind in (b"MODE2", b"MODE2_RAW"):
                subheader = 16 if kind == b"MODE2_RAW" else 0

                if (
                    frame[subheader:subheader + 4] != frame[subheader + 4:subheader + 8]
                    or frame[subheader + 2] & 0x20
                ):
                    raise SourceError("CHD probe requires Mode 2 Form 1 service sectors", path=path)

            return frame[offset:offset + 2048]

        sega = read_sector(0).startswith(b"SEGADISCSYSTEM")
        pvd = read_sector(16)
        playstation = pvd[:7] == b"\x01CD001\x01" and pvd[8:40].rstrip(b" \0") == b"PLAYSTATION"

        if sega == playstation:
            raise SourceError("CHD platform is ambiguous or unrecognized (expected PSX or Sega CD)", path=path)

        if playstation and not _has_psx_boot_signature(read_sector, pvd, frames - start, path):
            raise SourceError("CHD has no PS1 boot signature (PS2 and unknown discs are unsupported)", path=path)

        return "SCD" if sega else "PSX"


def _has_psx_boot_signature(read_sector: Callable[[int], bytes], pvd: bytes, frames: int, path: Path) -> bool:
    # PS2 CDs also use PLAYSTATION. Inspect only the bounded root directory and
    # boot configuration, never descend through directories or scan executables.

    if pvd[128:132] != b"\x00\x08\x08\x00":
        raise SourceError("Unsupported CHD ISO logical block size", path=path)

    def read_extent(record: bytes, limit: int, *, prefix: bool = False) -> bytes:

        if len(record) < 34 or record[0] != len(record) or record[1] or record[26:28] != b"\0\0":
            raise SourceError("Invalid or interleaved CHD ISO directory record", path=path)

        lba, size = int.from_bytes(record[2:6], "little"), int.from_bytes(record[10:14], "little")

        if lba != int.from_bytes(record[6:10], "big") or size != int.from_bytes(record[14:18], "big"):
            raise SourceError("Inconsistent CHD ISO directory record", path=path)

        if not size or record[25] & 0x80 or lba + (size + 2047) // 2048 > frames:
            raise SourceError("Invalid or multi-extent CHD ISO file", path=path)

        if size > limit and not prefix:
            raise SourceError("CHD boot metadata exceeds its bounded probe limit", path=path)

        count = min(size, limit)
        return b"".join(read_sector(lba + number) for number in range((count + 2047) // 2048))[:count]

    root = pvd[156:156 + pvd[156]]

    if len(root) < 34 or not root[25] & 2:
        raise SourceError("Invalid CHD ISO root directory", path=path)

    directory = read_extent(root, 64 * 1024)
    files = {}
    position = 0

    while position < len(directory):
        length = directory[position]

        if not length:
            position = (position // 2048 + 1) * 2048
            continue

        record = directory[position:position + length]

        if len(record) != length or length < 34 or record[32] + 33 > length or position % 2048 + length > 2048:
            raise SourceError("Truncated CHD ISO directory record", path=path)

        name = record[33:33 + record[32]].upper()

        if name in (b"SYSTEM.CNF;1", b"PSX.EXE;1"):

            if name in files or record[25] & 2:
                raise SourceError("Ambiguous CHD ISO boot file", path=path)

            files[name] = record

        position += length

    if b"SYSTEM.CNF;1" in files:
        config = read_extent(files[b"SYSTEM.CNF;1"], 4096)
        boot = re.findall(rb"(?im)^\s*(BOOT2?)\s*=\s*([^\r\n\0]+)", config)
        return len(boot) == 1 and boot[0][0].upper() == b"BOOT" and boot[0][1].lower().startswith(b"cdrom:")

    return b"PSX.EXE;1" in files and read_extent(files[b"PSX.EXE;1"], 2048, prefix=True).startswith(b"PS-X EXE")
